[[main]]
name = "About Us"
pageRef = "about"
weight = 10

[[main]]
name = "Projects"
weight = 20

# [[main]]
# name = "Portable Milling"
# parent = "Projects"
# #pageRef = "services/portable_milling"
# weight = 20

# [[main]]
# name = "Build Design"
# parent = "Projects"
# #pageRef = "services/hacker_manifesto"
# weight = 20

# [[main]]
# name = "Construction"
# parent = "Projects"
# #pageRef = "services/technofeudalism"
# weight = 20

[[main]]
name = "Calender"
pageRef = "about"
weight = 30

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20

